meta-custom: platform-*-config: enhance scripts
Change-Id: I8e3fcec5f19147ac1fd465f61d393be839fcb253
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/meta-custom/recipes-platform/platform-device-config/files/platform-device-config b/meta-custom/recipes-platform/platform-device-config/files/platform-device-config
--- a/meta-custom/recipes-platform/platform-device-config/files/platform-device-config
+++ b/meta-custom/recipes-platform/platform-device-config/files/platform-device-config
@@ -7,45 +7,30 @@ MYNAME=$(basename $BASH_SOURCE)
 confdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)
 
 function info() { echo "$(basename $BASH_SOURCE) - $@" >&2; }
+function warning() { echo "$(basename $BASH_SOURCE) - WARNING: $@" >&2; }
 function error() { echo "$(basename $BASH_SOURCE) - ERROR: $@" >&2; }
 
-source /etc/platform-info/device
+DEVINFO=/etc/platform-info/devices
+
+[[ ! -f $DEVINFO ]] && { error "Unable to find $DEVINFO"; exit 1; }
+
+. $DEVINFO || { error "Unable to source $DEVINFO"; exit 2; }
  
 # --------------------------------------------------------------
-if [ -d ${confdir_default}/COMMON ]; then
+
+[[ -d ${confdir_default}/COMMON ]] && {
     for sc in $(ls ${confdir_default}/COMMON);do
         bash $dir/$sc
     done
-fi
+}
 
-if [ -n "${HW_BLUETOOTH_DEVICES}" ]; then
-    if [ -d ${confdir_default}/BLUETOOTH_DEVICES ]; then
-        for sc in $(ls ${confdir_default}/BLUETOOTH_DEVICES);do
-            bash $dir/$sc ${HW_BLUETOOTH_DEVICES}
-        done
-    fi
-fi
+for key in BLUETOOTH_DEVICES ETHERNET_DEVICES CAN_DEVICES WIFI_DEVICES; do
+	hwkey="HW_$key"
+	[[ -d ${confdir_default}/$key ]] && 
+	[[ -n "${!hwkey}" ]] && {
+		for sc in $(ls ${confdir_default}/COMMON);do
+			bash $dir/$sc ${!hwkey}
+		done
+	}
+done
 
-if [ -n "${HW_ETHERNET_DEVICES}" ]; then
-    if [ -d ${confdir_default}/ETHERNET_DEVICES ]; then
-        for sc in $(ls ${confdir_default}/ETHERNET_DEVICES);do
-            bash $dir/$sc ${HW_ETHERNET_DEVICES}
-        done
-    fi
-fi
-
-if [ -n "${HW_CAN_DEVICES}" ]; then
-    if [ -d ${confdir_default}/CAN_DEVICES ]; then
-        for sc in $(ls ${confdir_default}/CAN_DEVICES);do
-            bash $dir/$sc ${HW_CAN_DEVICES}
-        done
-    fi
-fi
-
-if [ -n "${HW_WIFI_DEVICES}" ]; then
-    if [ -d ${confdir_default}/WIFI_DEVICES ]; then
-        for sc in $(ls ${confdir_default}/WIFI_DEVICES);do
-            bash $dir/$sc ${HW_WIFI_DEVICES}
-        done
-    fi
-fi
diff --git a/meta-custom/recipes-platform/platform-hardware-config/files/platform-hardware-config b/meta-custom/recipes-platform/platform-hardware-config/files/platform-hardware-config
--- a/meta-custom/recipes-platform/platform-hardware-config/files/platform-hardware-config
+++ b/meta-custom/recipes-platform/platform-hardware-config/files/platform-hardware-config
@@ -7,22 +7,29 @@ MYNAME=$(basename $BASH_SOURCE)
 confdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)
 
 function info() { echo "$(basename $BASH_SOURCE) - $@" >&2; }
+function warning() { echo "$(basename $BASH_SOURCE) - WARNING: $@" >&2; }
 function error() { echo "$(basename $BASH_SOURCE) - ERROR: $@" >&2; }
 
-source /etc/platform-info/hardware
+HWINFO=/etc/platform-info/hardware
+
+[[ ! -f $HWINFO ]] && { error "Unable to find $HWINFO"; exit 1; }
+
+. $HWINFO || { error "Unable to source $HWINFO"; exit 2; }
  
 # --------------------------------------------------------------
 
-
 LISTDIR="${confdir_default}/COMMON"
-if [ -n "${HW_CPU_ARCH}" ];         then LISTDIR="${LISTDIR} ${confdir_default}/CPU_ARCH/${HW_CPU_ARCH}" ;fi
-if [ -n "${HW_SOC_VENDOR}" ];   then LISTDIR="${LISTDIR} ${confdir_default}/SOC_VENDOR/${HW_SOC_VENDOR}" ;fi
-if [ -n "${HW_BOARD_MODEL}" ];then LISTDIR="${LISTDIR} ${confdir_default}/BOARD_MODEL/${HW_BOARD_MODEL}" ;fi
+
+for key in CPU_ARCH SOC_VENDOR BOARD_MODEL; do
+	hwkey="HW_$key"
+	[[ -z "${!hwkey}" ]] && { warning "$hwkey is not set - please check $HWINFO"; continue; }
+	LISTDIR="${LISTDIR} ${confdir_default}/$key/${!hwkey}"
+done
 
 for dir in $LISTDIR; do
-	if [ -d $dir ]; then
+	[[ -d $dir ]] && {
 		for sc in $(ls $dir);do
 			bash $dir/$sc
 		done
-	fi
+	}
 done
