meta-custom: add platform-hardware-script.bbclass, add kingfisher-disable-btwilink.bb
The class helps to package scriptlets to be launched by platform-hardware-config

The script to disable btwilink module on KF has been migrated to a specific package

Change-Id: Id7ac2d0b59060825f05cfa0cfda941dd169f5b02
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/meta-custom/recipes-platform/platform-hardware-config/files/platform-hardware-config b/meta-custom/recipes-platform/platform-hardware-config/files/platform-hardware-config
--- a/meta-custom/recipes-platform/platform-hardware-config/files/platform-hardware-config
+++ b/meta-custom/recipes-platform/platform-hardware-config/files/platform-hardware-config
@@ -8,34 +8,41 @@
 set -e
 
 MYNAME=$(basename $BASH_SOURCE)
+CONFIGDIR=/etc/platform-info
 
-confdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)
+scriptdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)
 
-function info() { echo "$(basename $BASH_SOURCE) - $@" >&2; }
-function warning() { echo "$(basename $BASH_SOURCE) - WARNING: $@" >&2; }
-function error() { echo "$(basename $BASH_SOURCE) - ERROR: $@" >&2; }
+function info() { echo "$@" >&2; }
+function warning() { echo "WARNING: $@" >&2; }
+function error() { echo "ERROR: $@" >&2; }
 
 function run_script() {
 	local sc=$1; shift
 	info "Running: $sc $@"
-	bash $sc "$@"|| error "script $sc FAILED with $?"
+	bash $sc "$@"|| { error "script $sc FAILED with $?"; return 1; }
+
+	# check if script is only for firstboot based on its name
+	# if so, remove it to prevent further executions
+	local n=$(basename $sc)
+	if [[ "$n" =~ ^[0-9]+(FB|firstboot)_ ]]; then
+		info "Removing script $sc (firstboot only)"
+		rm $sc
+	fi
 	return 0
 }
 
+for x in hardware devices; do
+	infos=$CONFIGDIR/$x
+	[[ ! -f $infos ]] && continue;
+	. $infos || { error "Unable to source $infos"; exit 2; }
+done
 
-HWINFO=/etc/platform-info/hardware
-
-[[ ! -f $HWINFO ]] && { error "Unable to find $HWINFO"; exit 1; }
-
-. $HWINFO || { error "Unable to source $HWINFO"; exit 2; }
- 
 # --------------------------------------------------------------
 
 # always include 'common' dir
-LISTDIR="${confdir_default}/common"
+LISTDIR="${scriptdir_default}/common"
 
-# $HWINFO should contain some of the following keys: CPU_ARCH, SOC_VENDOR, ...
-# let's find which ones
+# environment must contain the following variables: CPU_ARCH, SOC_VENDOR, BOARD_MODEL
 CATEGORIES="\
    CPU_ARCH \
    SOC_VENDOR \
@@ -44,6 +51,8 @@ CATEGORIES="\
 for key in $CATEGORIES; do
 	hwkey="HW_$key"
 
+	[[ -z "${!hwkey}" ]] && { error "$hwkey is not set - please check files in $CONFIGDIR"; exit 1; }
+
 	# map key to folder name
 	case $hwkey in
 		CPU_ARCH)		dirname=arch;;
@@ -51,8 +60,8 @@ for key in $CATEGORIES; do
 		BOARD_MODEL)	dirname=board;;
 		*)				dirname=${key,,} # key in lowercase
 	esac
-	[[ -z "${!hwkey}" ]] && { warning "$hwkey is not set - please check $HWINFO"; continue; }
-	LISTDIR="${LISTDIR} ${confdir_default}/$dirname/${!hwkey}"
+
+	LISTDIR="${LISTDIR} ${scriptdir_default}/$dirname/${!hwkey}"
 done
 
 # then iterate on each found dir and run scripts inside
