meta-custom: add platform-hardware-script.bbclass, add kingfisher-disable-btwilink.bb
The class helps to package scriptlets to be launched by platform-hardware-config

The script to disable btwilink module on KF has been migrated to a specific package

Change-Id: Id7ac2d0b59060825f05cfa0cfda941dd169f5b02
Signed-off-by: Stephane Desneux <stephane.desneux@iot.bzh>

diff --git a/meta-custom/recipes-platform/platform-devices-config/files/platform-devices-config b/meta-custom/recipes-platform/platform-devices-config/files/platform-devices-config
--- a/meta-custom/recipes-platform/platform-devices-config/files/platform-devices-config
+++ b/meta-custom/recipes-platform/platform-devices-config/files/platform-devices-config
@@ -8,49 +8,67 @@
 set -e
 
 MYNAME=$(basename $BASH_SOURCE)
+CONFIGDIR=/etc/platform-info
 
-confdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)
+scriptdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)
 
-function info() { echo "$(basename $BASH_SOURCE) - $@" >&2; }
-function warning() { echo "$(basename $BASH_SOURCE) - WARNING: $@" >&2; }
-function error() { echo "$(basename $BASH_SOURCE) - ERROR: $@" >&2; }
+function info() { echo "$@" >&2; }
+function warning() { echo "WARNING: $@" >&2; }
+function error() { echo "ERROR: $@" >&2; }
 
 function run_script() {
 	local sc=$1; shift
 	info "Running: $sc $@"
-	bash $sc "$@"|| error "script $sc FAILED with $?"
+	bash $sc "$@"|| { error "script $sc FAILED with $?"; return 1; }
+
+	# check if script is only for firstboot based on its name
+	# if so, remove it to prevent further executions
+	local n=$(basename $sc)
+	if [[ "$n" =~ ^[0-9]+(FB|firstboot)_ ]]; then
+		info "Removing script $sc (firstboot only)"
+		rm $sc
+	fi
 	return 0
 }
 
-DEVINFO=/etc/platform-info/devices
+for x in hardware devices; do
+	infos=$CONFIGDIR/$x
+	[[ ! -f $infos ]] && continue;
+	. $infos || { error "Unable to source $infos"; exit 2; }
+done
 
-[[ ! -f $DEVINFO ]] && { error "Unable to find $DEVINFO"; exit 1; }
-
-. $DEVINFO || { error "Unable to source $DEVINFO"; exit 2; }
- 
 # --------------------------------------------------------------
 
-# run all scripts in 'common'
-[[ -d ${confdir_default}/common ]] && {
-	for sc in $(ls ${confdir_default}/common);do
-		run_script $dir/$sc
-	done
-}
+# always include 'common' dir
+LISTDIR="${scriptdir_default}/common"
 
-# keys are defined in /etc/platform-info/devices
+# environment must contain the following variables: CPU_ARCH, SOC_VENDOR, BOARD_MODEL
 CATEGORIES="\
-   BLUETOOTH_DEVICES \
-   ETHERNET_DEVICES \
-   CAN_DEVICES \
-   WIFI_DEVICES \
+   CPU_ARCH \
+   SOC_VENDOR \
+   BOARD_MODEL \
 "
 for key in $CATEGORIES; do
 	hwkey="HW_$key"
-	dirname=${key,,} # lowercase
-	if [[ -d ${confdir_default}/$key && -n "${!hwkey}" ]]; then
-		for sc in $(ls ${confdir_default}/$dirname);do
-			run_script $dir/$sc ${!hwkey}
+
+	[[ -z "${!hwkey}" ]] && { error "$hwkey is not set - please check files in $CONFIGDIR"; exit 1; }
+
+	# map key to folder name
+	case $hwkey in
+		CPU_ARCH)		dirname=arch;;
+		SOC_VENDOR)		dirname=vendor;;
+		BOARD_MODEL)	dirname=board;;
+		*)				dirname=${key,,} # key in lowercase
+	esac
+
+	LISTDIR="${LISTDIR} ${scriptdir_default}/$dirname/${!hwkey}"
+done
+
+# then iterate on each found dir and run scripts inside
+for dir in $LISTDIR; do
+	if [[ -d $dir ]]; then
+		for sc in $(ls $dir);do
+			run_script $dir/$sc
 		done
 	fi
 done
-
